### ISSUE TITLE
docgen doesn't create correct ts definition for rhino3dm js and py

### ISSUE THREAD

**Issue by fraguada** [mcneel/rhino3dm#376]
Example: 

https://github.com/mcneel/rhino3dm/blob/master/src/bindings/bnd_surface.h#L33
```javascript
BND_TUPLE FrameAt(double u, double v);
```
results in:
```typescript
/**
* @description Computes the orient plane on a surface given a U and V parameter.
		This is the simple evaluation call with no error handling.
* @param {number} u A first parameter.
* @param {number} v A second parameter.
* @param {Plane} frame A frame plane that will be computed during this call.
* @returns {boolean} true if this operation succeeded; otherwise false.
*/
frameAt(u:number,v:number,frame:Plane): boolean;
```

**Comment by pearswj** [comment]
If you investigate this, can you take a look at #349? It should make working with docgen a little easier.

**Comment by fraguada** [comment]
Yes! That will be really useful.

**Comment by fraguada** [comment]
Editing this issue because the same is the case for python. For example:
RhinoCommon: https://developer.rhino3d.com/api/RhinoCommon/html/M_Rhino_Geometry_Intersect_Intersection_LinePlane.htm

```csharp
public static bool LinePlane(
	Line line,
	Plane plane,
	out double lineParameter
)
```

Binding code:
```cpp
BND_TUPLE BND_Intersection::PlanePlane(const BND_Plane& planeA, const BND_Plane& planeB)
{
  ON_Line line;
  bool success = ON_Intersect(planeA.ToOnPlane(), planeB.ToOnPlane(), line);
  BND_TUPLE rc = CreateTuple(2);
  SetTuple(rc, 0, success);
  SetTuple(rc, 1, line);
  return rc;
}
```

rhino3dm.py: https://mcneel.github.io/rhino3dm/python/api/Intersection.html#rhino3dm.Intersection.LinePlane
<img width="703" alt="image" src="https://user-images.githubusercontent.com/1014562/119808070-0d4e7a80-bee4-11eb-9ad9-c29c268cb2fa.png">

rhino3dm.js: https://mcneel.github.io/rhino3dm/javascript/api/Intersection.html#.linePlane
<img width="1149" alt="image" src="https://user-images.githubusercontent.com/1014562/119808304-471f8100-bee4-11eb-9ecf-6a0b2286967d.png">

**Comment by sbaer** [comment]
we need to handle functions with `out` parameters as returning tuples
