### ISSUE TITLE
Update Apple tools to macOS 11.5.2, Xcode 12.5, etc

### ISSUE THREAD

**Issue by dan-rigdon-bel** [mcneel/rhino3dm#413]
Update bootstrap to use:

- macOS 11.5.2
- Xcode 12.5
- Xamarin.iOS 14.14.2.5
- Mono MDK 6.12.0.107

In addition, modify the macOS check to use new-school macOS version numbers (11)

**Comment by dbelcher** [comment]
To get it to play-nice with Xcode 12.5, this requires updating CMake to 3.21.1 as well.  This will need testing on Windows.

**Comment by fraguada** [comment]
resolved
