### ISSUE TITLE
not able to install  the pip rhino3dm

### ISSUE THREAD

**Issue by ashad62** [mcneel/rhino3dm#416]
Hello there, I'm not able to install the pip for rhino3dm, I'm getting a error stating the following screenshot I shared. it would be helpful if you could help me. Thank you.
![Screenshot (88)](https://user-images.githubusercontent.com/78596289/132944025-6ef4d9b6-8510-42d6-9d9e-30bf9df3dd24.png)

**Comment by sbaer** [comment]
This is probably because you are using a 32 bit version of python. You will probably have better luck using a 64 bit version.
