### ISSUE TITLE
Create new groups in File3dm

### ISSUE THREAD

**Issue by cedemax** [mcneel/rhino3dm#417]
It seems that there is no way to add groups/group objects when creating a new File3DM object. This would be very useful, as groups are a great feature. Is there a reason why groups cannot be created? 

There are methods on `ObjectAttributes` to add to groups and remove from groups, but these don't seem to create new groups?

**Comment by sbaer** [comment]
I looks like we need to expose some additional Add routines to the GroupTable on File3dm

**Comment by fraguada** [comment]
fyi, this already works in js and py

**Comment by fraguada** [comment]
We will need to add a way to create a group object outside of Rhino SDK.

**Comment by fraguada** [comment]
This has been added via https://github.com/mcneel/rhino3dm/pull/574
