### ISSUE TITLE
Include xml code documentation in nuget package

### ISSUE THREAD

**Issue by tebjan** [mcneel/rhino3dm#425]
It would be immensely helpful if the nuget package would include the code documentation XML file. Currently one has to download the source code and do a reverse search for the method to read the code doc.

This can be easily done by setting some build properties: https://stackoverflow.com/questions/5205738/how-do-you-include-xml-docs-for-a-class-library-in-a-nuget-package

**Comment by fraguada** [comment]
this has been included in rhino3dm8.0.0-beta3
