### ISSUE TITLE
InstanceDefinitionGeometry.SourceArchive

### ISSUE THREAD

**Issue by sbaer** [mcneel/rhino3dm#427]
See: https://discourse.mcneel.com/t/how-to-load-geometry-from-linked-block-files/133177/6

InstanceDefinitionGeometry needs a SourceArchive property. This was accidentally placed on the InstanceDefinition class in RhinoCommon

**Comment by fraguada** [comment]
This has been available in dotnet since 8.0.0-beta. I recommend you check Rhino3dm 8.0.0-beta3
