### ISSUE TITLE
Python 3.10 Support

### ISSUE THREAD

**Issue by sbaer** [mcneel/rhino3dm#428]
We need to start building a binary distribution for Python 3.10

**Comment by fraguada** [comment]
Added python 310 to

- workflow_ci build_py_all_bdist matrix
- workflow_release build_py_all_bdist matrix

Testing builds now on workflow_ci seems to work ok. Anywhere else we need to add 3.10?

**Comment by fraguada** [comment]
@sbaer check the artifacts of this workflow run: https://github.com/mcneel/rhino3dm/actions/runs/1461953321
There should be python 3.10 releases for linux, macos, and windows.
