### ISSUE TITLE
rhino3dm.js Module type definition aka rhino3dm.d.ts is a really mess!

### ISSUE THREAD

**Issue by KaivnD** [mcneel/rhino3dm#433]
As you can see in the title, so much error in type definition file `rhino3dm.d.ts`.
Few yeas ago, I found this module, which really got my attention. I like it, but when I use it with typescript, oh no, so much to `// @ts-ignore`, it really drive me mad, so I decided try to make things right, only if you guys let me, I can make pr for this.

**Comment by sbaer** [comment]
Feel free to submit a PR. This would require updating the ts file generator. The code that creates the ts file is at
https://github.com/mcneel/rhino3dm/blob/main/src/docgen/JavascriptClass.cs#L206

**Comment by fraguada** [comment]
related to #431

**Comment by fraguada** [comment]
Closing this as we're tracking the fixes to d.ts in #470 and #431
