### ISSUE TITLE
Wrap Length getters for curve types

### ISSUE THREAD

**Issue by fraguada** [mcneel/rhino3dm#439]
From: https://discourse.mcneel.com/t/is-it-possible-that-not-all-api-are-exposed-in-net/136440/5

**Comment by fraguada** [comment]
openNURBS has a length property for lines, arcs, and polylines.

**Comment by dalefugier** [comment]
This is something we don't provide in the free openNURBS toolkit. Thus, it won't be provided in the free Rhino3dm toolkit.

**Comment by fraguada** [comment]
Hello @dalefugier these exist in openNURBS for lines, arcs, and polylines, so please keep this open until those are wrapped.

**Comment by fraguada** [comment]
Verified that these are already wrapped for lines, arcs, and polylines.
