### ISSUE TITLE
build rhino3dm 7.15.0: can't open file '/tools/webidl_binder.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by icjking** [mcneel/rhino3dm#475]
> Dear all：
    I encountered a compilation error, indicating a missing file. Did I lose it when I pulled git? Or do i need to set something else? Thanks to correct me
> 
> ```
> /Users/xxx/work/rhino3dm/venv/bin/python: can't open file '/tools/webidl_binder.py': [Errno 2] No such file or directory
> CMake Error at lib/draco/CMakeLists.txt:695 (message):
>  Glue generation failed.
>  emcmake: error: 'cmake ../.. -DCMAKE_TOOLCHAIN_FILE=/Users/xxx/work/software/emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake -DCMAKE_CROSSCOMPILING_EMULATOR=/Users/xxx/work/software/emsdk/node/14.18.2_64bit/bin/node;--experimental-wasm-threads' failed (returned 1)
> Configuring incomplete, errors occurred!
> ```
> 
> Thanks for taking a look

**Comment by pearswj** [comment]
We're still using Emscripten SDK 2.0.10, so I'd recommend using that version for the time being.

The current latest version (3.1.28) doesn't define the `EMSCRIPTEN` env var and this throws off the version of Draco that we use. You can get around this by setting `EMSCRIPTEN` to the path of the parent directory of the Emscripten tools directory. However, compiling will result in an error when applying the JS module patch; this can be commented out to get a successful build but it's untested and will need to be looked into.

https://github.com/google/draco/blob/e4e34b0c63d631ec5eefa3c41bfd5dab868b82de/BUILDING.md#javascript-encoderdecoder
