### ISSUE TITLE
Intersect.Intersection.BrepBrep method

### ISSUE THREAD

**Issue by stgeorges** [mcneel/rhino3dm#511]
Hello @fraguada ,
Do you think at some point in future rhino3dm can get the "Intersect.Intersection.BrepBrep" method?

**Comment by fraguada** [comment]
Hello @stgeorges. No. This method is not something in OpenNURBS and requires full Rhino to calculate.

**Comment by stgeorges** [comment]
Thank you for the reply Luis.
