### ISSUE TITLE
Can't access Brep.IsPointInside function

### ISSUE THREAD

**Issue by codingmanu** [mcneel/rhino3dm#514]
Very new to C#. I'm using Rhino3dm on .NET and I'm able to open files and extract information from the 3dm model as needed. The issue I'm having now is that I'm seeing a function called `IsPointInside` inside the `opennurbs_brep.cs` file but I'm not able to use that function in my code. Do I need to import anything special? Is that function just not exposed?

I'm seeing the function after `#if RHINO_SDK`. Is that flag something I can add to my Visual Studio?

The main purpose of my program is to find which object contains a certain point passing its coordinates. I'm able to do this in Python as a script in Rhino, but wanted to try to make it faster with Rhino3dm and also not depend on Rhino so other users can run this program. Is this possible at all?

Rough code I'm trying to build:
```csharp
static void FindSpace(File3dm file, Point3d point)
{
    File3dmObjectTable objects = file.Objects;

    foreach (var rhinoObject in objects.Where(obj => obj.Geometry.ObjectType == ObjectType.Brep || obj.Geometry.ObjectType == ObjectType.Extrusion))
    {
        Brep brepObject = Brep.TryConvertBrep(rhinoObject.Geometry);
        if (brepObject != null)
        {
            bool isInside = brepObject.IsPointInside(point);
            if (isInside)
            {
                Console.WriteLine("Point is inside solid named: " + rhinoObject.Name);
            }
        }
    }
}
```

My error:
![Screenshot 2023-04-05 at 6 58 48 PM](https://user-images.githubusercontent.com/6534819/230230238-526a985b-e607-4c3b-9ca8-c12e9ccce150.png)

Thanks!

**Comment by sbaer** [comment]
Functions inside of #if RHINO_SDK blocks are only available in RhinoCommon when running inside of Rhino. Rhino3dm and RhinoCommon share the same .NET source code which is why you see it in this repo.
