### ISSUE TITLE
 rhino3dm support for Godot Engine

### ISSUE THREAD

**Issue by fire** [mcneel/rhino3dm#518]
Hi,

I was wondering what would be more expedient way to support Godot Engine import and export of 3DM. I can be capable at C++, but I wanted to know what flows are easier than others.

Godot's main import / export format is GLTF which is a triangle based physically based 3d format with skeleton and node animations.

Thanks

**Comment by sbaer** [comment]
It sounds like you need a 3dm to gltf converter. Rhino supports gltf export.

**Comment by fire** [comment]
Is there anything standalone?

**Comment by fraguada** [comment]
You can go from 3dm to gltf with the threejs 3dmLoader and gltf exporter.

**Comment by fire** [comment]
So ship electron and then make a three js app. That’s approximately a little more than godot engines size footprint but feasible.
