### ISSUE TITLE
Rhino 7 can't open a file3dm created with rhino3dm.js v8

### ISSUE THREAD

**Issue by dgrcode** [mcneel/rhino3dm#521]
I just created a 3dm file with the rhino3dm.js library v8, and it gave me an error when trying to open it with Rhino. It said something like the file had been created with Rhino 8 and it couldn't be opened with Rhino 7. I haven't seen any Rhino 8 available yet.

The exact error message is:
```
The model named {path to file} was created by Rhino 8.
This model cannot be read by Rhino 7.
 For information about the latest version of Rhino visit http://www.rhino3d.com
```

Is that expected?

**Comment by fraguada** [comment]
@dgrcode yes. rhino3dm 8 version will default to saving Rhino 8 files. Just keep in mind when saving:

```javascript
//...
const options = new rhino.File3dmWriteOptions()
options.version = 7
let buffer = doc.toByteArray(options)
//...
```

**Comment by dgrcode** [comment]
That worked great. Thanks! :)
