### ISSUE TITLE
Unassigned materials are missing

### ISSUE THREAD

**Issue by harrycollin** [mcneel/rhino3dm#611]
Materials defined in Rhino but not assigned to an object aren't present in the rhino3dm.js. It seem that only materials that are attached to an object are loaded. Is this expected behavior?

**Comment by fraguada** [comment]
@harrycollin unassigned materials can be found in the document's Render Content list. Check out this sample: https://github.com/mcneel/rhino-developer-samples/blob/8/rhino3dm/js/node/Samples/ReadDocMaterials.js

Let me know if that works for you.

**Comment by harrycollin** [comment]
@fraguada Thank you. I'll take a look :)
