### ISSUE TITLE
Fail Brep.CreateFromMesh()

### ISSUE THREAD

**Issue by Cool-key** [mcneel/rhino3dm#637]
code

![20240906155813](https://github.com/user-attachments/assets/1c0bc461-49b9-47ed-8863-781ba2daf716)
[points.txt](https://github.com/user-attachments/files/16904827/points.txt)

mesh.Normals.ComputeNormals();
mesh.Compact();
string str = SolidCoreLib.Storage_Method.ObjectToJson(mesh.Faces.Select(r=>new List<double[]> { new double[] { mesh.Vertices.ElementAt(r.A).X, mesh.Vertices.ElementAt(r.A).Y, mesh.Vertices.ElementAt(r.A).Z }, new double[] { mesh.Vertices.ElementAt(r.B).X, mesh.Vertices.ElementAt(r.B).Y, mesh.Vertices.ElementAt(r.B).Z }, new double[] { mesh.Vertices.ElementAt(r.C).X, mesh.Vertices.ElementAt(r.C).Y, mesh.Vertices.ElementAt(r.C).Z } }).ToList());
Brep brep =Brep.CreateFromMesh(mesh,false);

brep==NULL

**Comment by sbaer** [comment]
Is this a bug report?

**Comment by Cool-key** [comment]
This is not a bug report，points file make up the vertices of the mesh，Running  code ，return brep is null.
mesh.Normals.ComputeNormals();
mesh.Compact();
Brep brep =Brep.CreateFromMesh(mesh,false);

**Comment by Cool-key** [comment]
Mesh cannot be converted to brep
