### ISSUE TITLE
[Python] File3dmObjectTable.__getitem__() does not accept negative indexing

### ISSUE THREAD

**Issue by StudioWEngineers** [mcneel/rhino3dm#651]
In Python negative indexing is possible, so I would expect this to work:
```
import rhino3dm

model = rhino3dm.File3dm()

for i in range(2):
    model.Objects.AddPoint(rhino3dm.Point3d(i, 0, 0))
    print(model.Objects[-1].Geometry.Location)

print(model.Objects[-2].Geometry.Location)
```
However, this does not work because of: https://github.com/mcneel/rhino3dm/blob/2be29689d99a9b8c0b511e3646cbe38a0bad6a81/src/bindings/bnd_extensions.cpp#L674

I would be happy to prepare a PR to make the behaviour of `File3dmObjectTable.__getitem__()` closer to a Python `list`, but I am wondering if this would be considered acceptable.

**Comment by sbaer** [comment]
I don't see any downside to supporting negative indexing
